##Questions

###Numbers

If you add an integer to a float, what is the output of the type?

Is a print statement required to print a calculation in Google Colab?

Are the types of 1 and 2.5 equal to, greater than, or greater than or equal to? Please try each example just to see what is the output.

Compute 4! using an external library.

Round -3.5

Find Min of -3.5,100,-101,303,-101.25

Solve  8รท2(2+2) computationally

###Strings

Can you slice "hungry" to obtain "un" but only with negative indices? Now try again with one positive index and one negative index.

Replace any two adjacent characters in "snow". Bonus points if you can spell a new word!

Split "supercalifragilisticexpialidocious" everytime you see an i, computationally.

Use a string method to convert "HELLO" into lowercase. Hint: Check Python documentation.

Print "I am Sam. Sam I am." solely using variables and punctuation two different ways using:
1.   String Formatting
2.   Concatenation

Hint: Initalize three different variables for "I", "am" and "Sam".

In [4]:
phrase = "{}{}{}{}{}{}{}{}{}"
iam = "I am"
sam = "Sam"
space = " "
period = "."
print(iam + space + sam + period + space + sam + space + iam + period)
print(phrase.format(iam, space, sam, period, space, sam, space, iam, period))

I am Sam. Sam I am.
I am Sam. Sam I am.

Make the following face using one print statement and escape sequences.


```
| |
 <
 O
```

In [6]:
print("| |\n < \n O ")

| |
 <
 O

###Lists

Determine how many times 1 appears in [1,4,5,1,3,1,1,4]. 

Hint: Refer to python documentation and use an existing list method

In [8]:
print([1,4,5,1,3,1,1,4].count(1))

4

Initialize a variable by setting it equal to the following list:

```
[1,2,5,6]
```

and set that same variable to the above list repeated 9 times.

In [11]:
a = [1,2,5,6]
a *= 9
a

[1,
 2,
 5,
 6,
 1,
 2,
 5,
 6,
 1,
 2,
 5,
 6,
 1,
 2,
 5,
 6,
 1,
 2,
 5,
 6,
 1,
 2,
 5,
 6,
 1,
 2,
 5,
 6,
 1,
 2,
 5,
 6,
 1,
 2,
 5,
 6]

Guess the output of the index function when we want to find out what the index of the value 1 is in the following list:

```
[3,1,1,2]
```
and then test it out yourself!

In [13]:
a = [3,1,1,2]
print("guess: 1")
a.index(1)

guess: 1

1

Remove all occurrences of 2's in the following list
```
[2,4,5,6,2]
```

In [0]:
l = [2,4,5,6,2]
while 2 in l:
  l.remove(2)

Initialize a list that has the following properties:



1.   List has length 4
2.   Each element of the list is a list of length 5

In [15]:
l = [[1]*5]*4
l

[[1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]]

What happens when you cast a list to a string?

In [20]:
str([1, "hy", "pe", ["Y", "es"]])

"[1, 'hy', 'pe', ['Y', 'es']]"

What happens when you cast a string to a list?

In [21]:
list("Hello World!")

['H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd', '!']

Can you convert 



```
["came", "saw", "conquered"]
```
using join (check Python documentation) to 

```
"came. I saw. I conquered"
```
and then use string concatentation to write

```
"I came. I saw. I conquered."
```
? Please be careful of spaces and punctuation.

In [23]:
a = ["came", "saw", "conquered"]
b = ". I "
c = "I "
d = "."
print(c + b.join(a) + d)

I came. I saw. I conquered.

###Tuples

Print the following statment out

```
"Hello, I have (3,4,5) blue, green and red socks respectively for a total of 12 socks."
```
except substitute both (3,4,5) and 12 with variables in your print statement. You will need to first initialize separate values for the tuple and the integer. Please get the spacing right!

Hint: If you are running into errors, think about what was thought in this lesson!

In [24]:
a = (3, 4, 5)
b = 12
c = "Hello, I have {} blue, green and red socks respectively for a total of {} socks."
print(c.format(a, b))

Hello, I have (3, 4, 5) blue, green and red socks respectively for a total of 12 socks.

###Sets

Get the length of this set: {1,5,7,8}

In [25]:
len({1,5,7,8})

4

Create a set {1,5,7,8}. Add 9 to the set. Pop the last element of the set. What is left in the set?

In [26]:
a = {1,5,7,8}
a.add(9)
a.pop()
a

{5, 7, 8, 9}

Initalize an empty set. Add 5 to the set twice. What is in the set now?

In [30]:
a = set()
a.update([5, 5])
a

{5}

###Dictionaries

Can a tuple be a dictionary key? Can it be a dictionary value?

In [33]:
a = {(2, 3) : "hello"}
print(a[(2, 3)])
a = {"hello": (1, 2)}
print(a["hello"])

hello
(1, 2)

Initialize a Dictionary of Dictionaries by mapping integer keys to dictionaries

In [34]:
dictionary = {0 : {"hello" : "kitty", "harry" : "potter"}, 1 : {"hello" : "dolly", "harry" : "houdini"}}
dictionary[1]

{'harry': 'houdini', 'hello': 'dolly'}